create database SHOPQUANAO
use SHOPQUANAO

drop table CATEGORY
CREATE TABLE CATEGORY(
	CATEID nvarchar(10) NOT NULL,
	CATENAME nvarchar(max) NOT NULL,
	primary key(CATEID)
)

DROP TABLE PRODUCT
CREATE TABLE PRODUCT(
	PRODUCTID BIGINT IDENTITY (1, 1),
	PRODUCTNAME NVARCHAR(MAX) NOT NULL,
	PRICE FLOAT NOT NULL,
	QUANTITY INT NOT NULL,
	CATEID NVARCHAR(10) NOT NULL,
	IMAGE NVARCHAR(MAX),
	DATECREATE DATETIME,
	PRIMARY KEY(PRODUCTID),
	FOREIGN KEY (CATEID) REFERENCES CATEGORY(CATEID) ON UPDATE CASCADE ON DELETE CASCADE
)
DROP TABLE ACCOUNT
CREATE TABLE ACCOUNT(
	USERNAME NVARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(MAX) NOT NULL,
	EMAIL NVARCHAR(MAX) NOT NULL,
	PHONE NVARCHAR(12) NOT NULL,
	GENDER BIT NOT NULL,
	ADDRESS NVARCHAR(MAX) NOT NULL,
	PHOTO NVARCHAR(MAX),
	PRIMARY KEY(USERNAME)
)
DROP TABLE CART
CREATE TABLE CART(
	CARTID BIGINT IDENTITY (1, 1),
	DATECART DATETIME NOT NULL,
	PHONE VARCHAR(12) NOT NULL,
	ADDRESS nvarchar(MAX) NOT NULL,
	USERNAME NVARCHAR(50) NOT NULL,
	PRIMARY KEY(CARTID),
	FOREIGN KEY (USERNAME) REFERENCES ACCOUNT(USERNAME) ON UPDATE CASCADE ON DELETE CASCADE
)
DROP TABLE BILL
CREATE TABLE BILL(
	BILLID BIGINT IDENTITY (1, 1) NOT NULL,
	QUANTITY INT NOT NULL,
	SUMPRICE FLOAT NOT NULL,
	STATUS NVARCHAR(MAX) NOT NULL,
	CARTID BIGINT,
	PRODUCTID BIGINT NOT NULL,
	PRIMARY KEY (BILLID),
	FOREIGN KEY (CARTID) REFERENCES CART(CARTID) ON UPDATE CASCADE ON DELETE SET NULL,
	FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID) ON UPDATE CASCADE ON DELETE CASCADE
)




DROP TABLE FAVORITE
CREATE TABLE FAVORITE(
	FAVID BIGINT IDENTITY (1, 1) NOT NULL,
	FAVDATE DATE NOT NULL,
	PRODUCTID BIGINT NOT NULL,
	USERNAME NVARCHAR(50) NOT NULL,
	PRIMARY KEY(FAVID),
	FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (USERNAME) REFERENCES ACCOUNT(USERNAME) ON UPDATE CASCADE ON DELETE CASCADE
)



DROP TABLE COMMENT
CREATE TABLE COMMENT(
	CMTID BIGINT IDENTITY (1, 1) NOT NULL,
	CMTDATE DATE NOT NULL,
	PRODUCTID BIGINT NOT NULL,
	USERNAME NVARCHAR(50) NOT NULL,
	PRIMARY KEY(CMTID),
	FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (USERNAME) REFERENCES ACCOUNT(USERNAME) ON UPDATE CASCADE ON DELETE CASCADE
)

DROP TABLE ROLE
CREATE TABLE ROLE(
	ROLEID NVARCHAR(10) NOT NULL,
	ROLENAME NVARCHAR(MAX) NOT NULL,
	PRIMARY KEY(ROLEID)
)

DROP TABLE ROLEACC
CREATE TABLE ROLEACC(
	ROLEACCID BIGINT IDENTITY (1, 1) NOT NULL,
	USERNAME NVARCHAR(50) NOT NULL,
	ROLEID NVARCHAR(10) NOT NULL,
	PRIMARY KEY(ROLEACCID),
	FOREIGN KEY (USERNAME) REFERENCES ACCOUNT(USERNAME) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (ROLEID) REFERENCES ROLE(ROLEID) ON UPDATE CASCADE ON DELETE CASCADE
)


